server:
  port: 9095

spring:
    datasource:
        name: test
        url: jdbc:mysql://106.13.66.110:3306/AI?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: SEBiw9360#
        driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
         connection-test-query: SELECT 1 FROM DUAL
         connection-init-sql: SET NAMES utf8mb4
         minimum-idle: 10   # 最小空闲连接数量
         idle-timeout: 180000   #  空闲连接存活最大时间，默认600000（10分钟）
         maximum-pool-size: 50 # 连接池最大连接数，默认是10
         auto-commit: true # 控制从池返回的链接的默认自动提交行为，默认值：true
         pool-name: MyHikariCP # 连接池母子
         max-lifetime: 1800000 # 控制池中链接的最长生命周期，值0表示无限生命周期，默认1800000，即30分钟
         connection-timeout: 600000 # 数据库链接超时时间，默认30秒，即30000
         validation-timeout: 3000
    redis:
        database: 2
        host: 106.13.66.110
        port: 6379
        password: IEG792`@*s
        pool:
          max-active: 100 #连接池最大连接数（负值表示没有限制）
          max-wait: 3000 #连接池最大阻塞等待时间（负值表示没有限制）
          max-idle: 200 #连接池最大空闭连接数
          min-idle: 50 #连接汉最小空闲连接数
          timeout: 6000 #连接超时时间（毫秒）
    servlet:
        multipart:
          max-file-size: 60MB #单个文件最大为60M
          max-request-size: 60MB #单次请求文件总数大小为20M

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.stla.expressage.bean
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


fileUrl: http://xiaoduo.poteit.com/files/

#redis登录存活时长
loginTimRedis: 2400

#七牛音频资源空间-生成视频资源
qiniuDownLoad: http://xdoss.poteit.com/
#七牛主空间-web资源
qiniuMain: http://xdxnrx.poteit.com/

DownLoadFile: http://xiaoduo.poteit.com/files/qiniu/

#对接U3D生成视频服务
httpWebUrl: http://40i469c523.zicp.vip
